Importing required libraries

In [5]:
import pandas as pd
import numpy as np

Importing the dataset

In [6]:
# loading the dataset into pandas dataFrame

movies_dataset = pd.read_csv(r"C:\Users\Vikash Kumawat\Desktop\DATASETS\tmdb_movies_dataset\tmdb_5000_movies.csv")
credits_dataset = pd.read_csv(r"C:\Users\Vikash Kumawat\Desktop\DATASETS\tmdb_movies_dataset\tmdb_5000_credits.csv")

In [7]:
# first five rows of the movies dataset
movies_dataset.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [8]:
# shape of the dataset

movies_dataset.shape

(4803, 20)

In [9]:
# columns in movies dataset

movies_dataset.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [10]:
# Print First 5 rows of the credits dataset

credits_dataset.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
# shape of the dataset

credits_dataset.shape

(4803, 4)

In [12]:
# columns in credits dataset

credits_dataset.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [13]:
# Now merging the both dataset

movies_dataset = movies_dataset.merge(credits_dataset, on='title')

In [14]:
movies_dataset.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
# shape of the new merged dataset

movies_dataset.shape

(4809, 23)

In [16]:
movies_dataset.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [17]:
movies_dataset = movies_dataset[['movie_id','title','overview','genres','keywords','cast','crew']]

In [18]:
movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
import ast

In [20]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [21]:
# checking the null values in the dataset

movies_dataset.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [22]:
# Here Null Values are very less so we can drop them

movies_dataset.dropna(inplace=True)

In [23]:
movies_dataset['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [24]:
movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
# using apply function 
movies_dataset['genres'] = movies_dataset['genres'].apply(convert)

In [26]:
movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
# using apply function on keywords
movies_dataset['keywords'] = movies_dataset['keywords'].apply(convert)

In [28]:
movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
# what ast.literal_eval does = Here it convert string to list


import ast
arr = ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')
print(arr)
type(arr)

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]

list

In [30]:
# Now again use ast.literal_eval on  'cast' column also in the dataset
def convert_cast(text):
  l = []
  counter = 0
  for i in ast.literal_eval(text):
    if counter < 3:
      l.append(i['name'])
    counter += 1
  return l

In [31]:
# apply() 
movies_dataset['cast'] = movies_dataset['cast'].apply(convert)

In [32]:
movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies_dataset['cast'] = movies_dataset['cast'].apply(lambda x:x[0:3])

movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [34]:
# fetching th director

def fetch_the_director(text):
  l = []
  for i in ast.literal_eval(text):
    if i['job'] == 'Director':
      l.append(i['name'])
  return l

In [35]:
movies_dataset['crew'] = movies_dataset['crew'].apply(fetch_the_director)

In [36]:
movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
# Replacing all the spaces

def collapse(l):
  l1 = []
  for i in l:
    l1.append(i.replace(" ",""))
  return l1

In [38]:
movies_dataset['cast'] = movies_dataset['cast'].apply(collapse)
movies_dataset['crew'] = movies_dataset['crew'].apply(collapse)
movies_dataset['genres'] = movies_dataset['genres'].apply(collapse)
movies_dataset['keywords'] = movies_dataset['keywords'].apply(collapse)

In [39]:
# print the first five rows of the dataset

movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [40]:
movies_dataset['overview'] = movies_dataset['overview'].apply(lambda x:x.split())

In [41]:
movies_dataset['tags'] = movies_dataset['overview'] + movies_dataset['genres'] + movies_dataset['keywords'] + movies_dataset['cast'] + movies_dataset['crew']

movies_dataset.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [42]:
new_movies_dataset = movies_dataset.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [43]:
new_movies_dataset['tags'] = new_movies_dataset['tags'].apply(lambda x: " ".join(x))
new_movies_dataset.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words = 'english')

In [45]:
vector = cv.fit_transform(new_movies_dataset['tags']).toarray()

In [46]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breast',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colombia',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 ...]

In [49]:
vector.shape

(4806, 5000)

Apply stemming on bag of words using NLTK library

In [50]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [51]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))
    return " ".join(y)

In [52]:
new_movies_dataset['tags'] = new_movies_dataset['tags'].apply(stem)

In [53]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breast',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colombia',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 ...]

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

0 = similarity low

1 = similarity high

In [55]:
similarity  = cosine_similarity(vector)

In [56]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [57]:
new_movies_dataset[new_movies_dataset['title'] == 'The Lego Movie'].index[0]

744

Recommend top 5 related movies

In [58]:
def recommend(movie):
  movie_index = new_movies_dataset[new_movies_dataset['title'] == movie].index[0]
  distances = sorted(list(enumerate(similarity[movie_index])), reverse= True, key=lambda x:x[1])
  for i in distances[1:6]:
    print(new_movies_dataset.iloc[i[0]].title)

In [59]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
The Avengers

Saving the model

In [60]:
import pickle

In [68]:
pickle.dump(new_movies_dataset, open('movies_list.pkl', 'wb'))

In [69]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [66]:
import requests
response = requests.get("https://api.themoviedb.org/3/movie/65?api_key=3bb1c16704a3213fff44b3bbc2da5c34&language=en-US")
data = response.json()
print(data['poster_path'])

/7BmQj8qE1FLuLTf7Xjf9sdIHzoa.jpg

In [67]:
print("https://image.tmdb.org/t/p/w500/" + data['poster_path'])

https://image.tmdb.org/t/p/w500//7BmQj8qE1FLuLTf7Xjf9sdIHzoa.jpg

In [64]:
def fetch_poster(movie_id):
    response = requests.get(f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=3bb1c16704a3213fff44b3bbc2da5c34&language=en-US")
    data = response.json()
    return "https://image.tmdb.org/t/p/w500/" + data['poster_path']
    
fetch_poster(65)

'https://image.tmdb.org/t/p/w500//7BmQj8qE1FLuLTf7Xjf9sdIHzoa.jpg'